#!/usr/bin/env bash

set -e

mkdir -p /run/devmode
mkdir -p /run/devmode/usr/u
mkdir -p /run/devmode/usr/w
mkdir -p /run/devmode/dpkg/u
mkdir -p /run/devmode/dpkg/w
mkdir -p /run/devmode/apt/u
mkdir -p /run/devmode/apt/w
mkdir -p /run/devmode/usr
mkdir -p /run/devmode/orig

mount --bind / /run/devmode/orig

mount -t overlay overlay -o lowerdir=/run/devmode/orig/usr,upperdir=/run/devmode/usr/u,workdir=/run/devmode/usr/w /usr
mount -t overlay overlay -o lowerdir=/run/devmode/orig/var/lib/dpkg,upperdir=/run/devmode/dpkg/u,workdir=/run/devmode/dpkg/w /var/lib/dpkg
mount -t overlay overlay -o lowerdir=/run/devmode/orig/var/lib/apt,upperdir=/run/devmode/apt/u,workdir=/run/devmode/apt/w /var/lib/apt
